# Generated by Django 2.0.2 on 2021-10-19 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('accounts', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='título de la actividad')),
                ('description', models.TextField(verbose_name='descripción de la actividad')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='fecha límite')),
                ('author_activity', models.CharField(blank=True, max_length=20, null=True, verbose_name='autor')),
                ('file_activity', models.FileField(blank=True, null=True, upload_to='', verbose_name='archivo adjunto de actividad')),
                ('is_completed', models.BooleanField(default=False, verbose_name='completado')),
                ('is_approved', models.CharField(choices=[('1', 'APROBADO A TIEMPO'), ('2', 'APROBADO CON RETRASO'), ('3', 'APROBADO CON MUCHO RETRASO')], max_length=1, null=True, verbose_name='aprobación de la actividad')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Project', verbose_name='proyecto')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
            },
        ),
        migrations.CreateModel(
            name='Criteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
                ('description', models.TextField(verbose_name='descripción')),
                ('weight', models.IntegerField(verbose_name='peso')),
            ],
            options={
                'verbose_name': 'criterio',
            },
        ),
        migrations.CreateModel(
            name='CriteriaProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.IntegerField(verbose_name='puntaje')),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracing.Criteria', verbose_name='criterio')),
                ('jury', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.ProfileJury', verbose_name='jurado')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Project', verbose_name='proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
                ('max_points', models.IntegerField(verbose_name='máximo de puntos')),
                ('date', models.DateField(verbose_name='fecha')),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Call', verbose_name='convocatoria')),
            ],
            options={
                'verbose_name': 'evaluación',
                'verbose_name_plural': 'evaluaciones',
            },
        ),
        migrations.CreateModel(
            name='EvaluationJury',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracing.Evaluation', verbose_name='evaluación')),
                ('jury', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.ProfileJury', verbose_name='jurado')),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='puntaje')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracing.Evaluation', verbose_name='evaluacion')),
                ('jury', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.ProfileJury', verbose_name='jurado')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Project', verbose_name='proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_score', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='puntaje')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracing.Evaluation', verbose_name='evaluación')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Project', verbose_name='proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, null=True, verbose_name='título')),
                ('description', models.TextField(null=True, verbose_name='descripción')),
                ('link', models.CharField(blank=True, max_length=200, null=True, verbose_name='link')),
                ('date', models.DateField(verbose_name='fecha')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='hora')),
                ('is_evaluated', models.BooleanField(default=False, verbose_name='evaluado')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Project', verbose_name='proyecto')),
            ],
            options={
                'verbose_name': 'entrevista',
                'verbose_name_plural': 'entrevistas',
            },
        ),
        migrations.CreateModel(
            name='Mentoring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='fecha')),
                ('time', models.TimeField(blank=True, null=True)),
                ('is_attended', models.CharField(choices=[('1', 'PENDIENTE'), ('2', 'ATENDIDO'), ('3', 'NO ATENDIDO')], default='1', max_length=1, verbose_name='estado de la mentoría')),
                ('observations', models.TextField(verbose_name='observaciones del mentor')),
                ('mentor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.ProfileMentor', verbose_name='mentor')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Project', verbose_name='proyecto')),
            ],
            options={
                'verbose_name': 'mentoría',
            },
        ),
        migrations.AddField(
            model_name='criteria',
            name='evaluation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracing.Evaluation', verbose_name='evaluación'),
        ),
        migrations.AlterUniqueTogether(
            name='evaluationjury',
            unique_together={('evaluation', 'jury')},
        ),
    ]
