# Generated by Django 2.0.2 on 2020-10-14 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0032_auto_20201008_1014'),
    ]

    operations = [
        migrations.CreateModel(
            name='Criteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
                ('description', models.TextField(verbose_name='descripción')),
                ('weight', models.IntegerField(verbose_name='peso')),
            ],
            options={
                'verbose_name': 'criterio',
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
                ('max_points', models.IntegerField(verbose_name='máximo de puntos')),
                ('date', models.DateField(verbose_name='fecha')),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Call', verbose_name='convocatoria')),
            ],
            options={
                'verbose_name': 'evaluación',
            },
        ),
        migrations.AddField(
            model_name='criteria',
            name='evaluation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracing.Evaluation', verbose_name='evaluación'),
        ),
    ]
