# Generated by Django 2.0.2 on 2020-10-21 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evaluation',
            options={'verbose_name': 'evaluación', 'verbose_name_plural': 'evaluaciones'},
        ),
    ]
