# Generated by Django 2.0.2 on 2020-10-22 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0033_auto_20201020_2221'),
        ('accounts', '0013_auto_20201020_2221'),
        ('tracing', '0002_auto_20201020_2221'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentoring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='fecha')),
                ('time', models.TimeField(blank=True, null=True)),
                ('is_attended', models.CharField(choices=[('1', 'NO ATENDIDO'), ('2', 'ATENDIDO')], default='1', max_length=1, verbose_name='estado de la mentoría')),
                ('observations', models.TextField(verbose_name='observaciones del mentor')),
                ('mentor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.ProfileMentor', verbose_name='mentor')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Project', verbose_name='proyecto')),
            ],
            options={
                'verbose_name': 'mentoría',
            },
        ),
    ]
