# Generated by Django 2.0.2 on 2020-10-22 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracing', '0003_mentoring'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentoring',
            name='is_attended',
            field=models.CharField(choices=[('1', 'PENDIENTE'), ('2', 'ATENDIDO'), ('3', 'NO ATENDIDO')], default='1', max_length=1, verbose_name='estado de la mentoría'),
        ),
    ]
