# Generated by Django 2.0.2 on 2020-10-24 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20201020_2221'),
        ('tracing', '0004_auto_20201022_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationJury',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracing.Evaluation', verbose_name='evaluación')),
                ('jury', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.ProfileJury', verbose_name='jurado')),
            ],
        ),
    ]
