# Generated by Django 2.0.2 on 2020-10-25 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20201020_2221'),
        ('tracing', '0005_evaluationjury'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='evaluationjury',
            unique_together={('evaluation', 'jury')},
        ),
    ]
