# Generated by Django 2.0.2 on 2020-10-26 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracing', '0006_auto_20201025_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluationjury',
            name='jury',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='jurado'),
        ),
    ]
