# Generated by Django 2.0.2 on 2020-10-26 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracing', '0007_auto_20201026_0701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluationjury',
            name='jury',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.ProfileJury', verbose_name='jurado'),
        ),
    ]
