# Generated by Django 2.0.2 on 2020-10-28 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0034_call_has_evaluations'),
        ('tracing', '0008_auto_20201026_0711'),
    ]

    operations = [
        migrations.CreateModel(
            name='CriteriaProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.IntegerField(verbose_name='puntos')),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracing.Criteria', verbose_name='criterio')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Project', verbose_name='proyecto')),
            ],
        ),
    ]
