# Generated by Django 2.0.2 on 2020-10-28 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracing', '0009_criteriaproject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criteriaproject',
            name='point',
            field=models.IntegerField(verbose_name='puntaje'),
        ),
    ]
