# Generated by Django 2.0.2 on 2020-10-29 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20201020_2221'),
        ('tracing', '0010_auto_20201028_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='criteriaproject',
            name='jury',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.ProfileJury', verbose_name='jurado'),
            preserve_default=False,
        ),
    ]
