# Generated by Django 2.0.2 on 2020-10-29 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0035_call_is_reviewed'),
        ('accounts', '0013_auto_20201020_2221'),
        ('tracing', '0011_criteriaproject_jury'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(verbose_name='puntaje')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracing.Evaluation', verbose_name='evaluacion')),
                ('jury', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.ProfileJury', verbose_name='jurado')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Project', verbose_name='proyecto')),
            ],
        ),
    ]
