# Generated by Django 2.0.2 on 2020-10-29 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracing', '0012_evaluationproject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluationproject',
            name='score',
            field=models.DecimalField(decimal_places=5, max_digits=10, verbose_name='puntaje'),
        ),
    ]
