# Generated by Django 2.0.2 on 2020-11-03 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracing', '0013_auto_20201029_1846'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='título de la actividad')),
                ('description', models.TextField(verbose_name='descripción de la actividad')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='fecha límite')),
                ('file_activity', models.FileField(upload_to='', verbose_name='archivo adjunto de actividad')),
            ],
        ),
    ]
