# Generated by Django 2.0.2 on 2020-11-03 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0039_auto_20201101_2136'),
        ('tracing', '0014_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='project',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='common.Project', verbose_name='proyecto'),
            preserve_default=False,
        ),
    ]
