# Generated by Django 2.0.2 on 2020-11-03 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracing', '0015_activity_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='name',
            new_name='title',
        ),
    ]
