# Generated by Django 2.0.2 on 2020-11-04 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracing', '0016_auto_20201103_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='file_activity',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='archivo adjunto de actividad'),
        ),
    ]
