# Generated by Django 2.0.2 on 2020-11-04 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracing', '0017_auto_20201104_1339'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name': 'Actividad', 'verbose_name_plural': 'Actividades'},
        ),
    ]
