# Generated by Django 2.0.2 on 2020-11-05 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0039_auto_20201101_2136'),
        ('tracing', '0018_auto_20201104_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_score', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='puntaje')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracing.Evaluation', verbose_name='evaluación')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Project', verbose_name='proyecto')),
            ],
        ),
    ]
