# Generated by Django 2.0.2 on 2020-11-17 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracing', '0019_evaluationsummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='completado'),
        ),
    ]
