# Generated by Django 2.0.2 on 2020-11-17 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracing', '0020_activity_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='is_approved',
            field=models.CharField(choices=[('1', 'APROBADO A TIEMPO'), ('2', 'APROBADO CON RETRASO'), ('3', 'APROBADO CON MUCHO RETRASO')], max_length=1, null=True, verbose_name='aprobación de la actividad'),
        ),
    ]
