# Generated by Django 2.0.2 on 2021-08-07 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracing', '0021_activity_is_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, null=True, verbose_name='título')),
                ('description', models.TextField(null=True, verbose_name='descripción')),
                ('link', models.CharField(blank=True, max_length=200, null=True, verbose_name='link')),
                ('date', models.DateField(verbose_name='fecha')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='hora')),
            ],
            options={
                'verbose_name': 'entrevista',
                'verbose_name_plural': 'entrevistas',
            },
        ),
    ]
