# Generated by Django 2.0.2 on 2021-08-07 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0047_merge_20210806_1942'),
        ('tracing', '0022_interview'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='common.Project', verbose_name='proyecto'),
            preserve_default=False,
        ),
    ]
