# Generated by Django 2.0.2 on 2021-10-20 02:37

import accounts.helpers
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(default='defaults/img/default-user.png', upload_to=accounts.helpers.profile_image_path)),
                ('dni', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator('^\\d{1,10}$', code='nomatch', message='Debe ser 8 digitos')], verbose_name='dni')),
                ('phone_number', models.CharField(max_length=15, verbose_name='telefono/celular')),
                ('specialty', models.CharField(max_length=100, verbose_name='especialidad')),
                ('birthday', models.DateField(verbose_name='fecha de nacimiento')),
                ('reason_to_belong', models.TextField(verbose_name='motivo por el que quieren pertenecer a la red de emprendedores Jaku')),
                ('is_pending', models.BooleanField(default=True)),
                ('temp_pwd', models.CharField(blank=True, max_length=10, null=True)),
                ('country', models.CharField(max_length=100, verbose_name='pais')),
                ('state', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='estado')),
                ('city', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='ciudad')),
                ('institution', models.CharField(max_length=100, verbose_name='institucion')),
                ('career', models.CharField(blank=True, max_length=100, null=True, verbose_name='carrera')),
                ('year_income', models.CharField(blank=True, max_length=100, null=True, verbose_name='anho_ingreso')),
                ('sex', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino'), ('N', 'No especifica')], max_length=1, verbose_name='sexo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileCoach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, verbose_name='telefono/celular')),
                ('habilitado', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileJury',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, verbose_name='telefono/celular')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileMentor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, verbose_name='telefono/celular')),
                ('specialty', models.CharField(max_length=150, verbose_name='especialidad')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
