# Generated by Django 2.0.2 on 2020-07-17 22:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190415_0657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='phone',
        ),
        migrations.AddField(
            model_name='profile',
            name='birthday',
            field=models.DateField(default='', verbose_name='fecha de nacimiento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='dni',
            field=models.CharField(default=1, max_length=8, verbose_name='dni'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.IntegerField(default=1, verbose_name='telefono/celular'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='reason_to_belong',
            field=models.TextField(default=1, verbose_name='motivo por el que quieren pertenecer a la red de emprendedores Jaku'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='specialty',
            field=models.CharField(default=1, max_length=20, verbose_name='especialidad'),
            preserve_default=False,
        ),
    ]
