# Generated by Django 2.0.2 on 2020-07-17 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200717_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_accepted',
            field=models.BooleanField(default=True),
        ),
    ]
