# Generated by Django 2.0.2 on 2020-07-18 03:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_is_accepted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='is_accepted',
            new_name='is_pending',
        ),
        migrations.AlterField(
            model_name='profile',
            name='dni',
            field=models.CharField(max_length=8, validators=[django.core.validators.RegexValidator(code='nomatch', message='Debe ser 8 digitos', regex='^.{8}$')], verbose_name='dni'),
        ),
    ]
