# Generated by Django 2.0.2 on 2020-07-19 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200717_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='temp_pwd',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
