# Generated by Django 2.0.2 on 2020-07-20 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_temp_pwd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='temp_pwd',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
