# Generated by Django 2.0.2 on 2020-07-23 19:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200720_0717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dni',
            field=models.CharField(max_length=8, validators=[django.core.validators.RegexValidator('^\\d{1,10}$', code='nomatch', message='Debe ser 8 digitos')], verbose_name='dni'),
        ),
    ]
