# Generated by Django 2.0.2 on 2020-10-19 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_profilecoach'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilecoach',
            name='phone_number',
            field=models.IntegerField(default=1, verbose_name='telefono/celular'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profilementor',
            name='specialty',
            field=models.CharField(default=1, max_length=150, verbose_name='especialidad'),
            preserve_default=False,
        ),
    ]
