# Generated by Django 2.0.2 on 2020-10-21 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20201019_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='specialty',
            field=models.CharField(max_length=100, verbose_name='especialidad'),
        ),
    ]
