# Generated by Django 2.0.2 on 2020-11-14 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20201020_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(max_length=15, verbose_name='telefono/celular'),
        ),
        migrations.AlterField(
            model_name='profilecoach',
            name='phone_number',
            field=models.CharField(max_length=15, verbose_name='telefono/celular'),
        ),
        migrations.AlterField(
            model_name='profilejury',
            name='phone_number',
            field=models.CharField(max_length=15, verbose_name='telefono/celular'),
        ),
        migrations.AlterField(
            model_name='profilementor',
            name='phone_number',
            field=models.CharField(max_length=15, verbose_name='telefono/celular'),
        ),
    ]
