# Generated by Django 2.0.2 on 2020-11-26 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20201113_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilecoach',
            name='phone_number',
            field=models.CharField(max_length=20, verbose_name='telefono/celular'),
        ),
        migrations.AlterField(
            model_name='profilejury',
            name='phone_number',
            field=models.CharField(max_length=20, verbose_name='telefono/celular'),
        ),
        migrations.AlterField(
            model_name='profilementor',
            name='phone_number',
            field=models.CharField(max_length=20, verbose_name='telefono/celular'),
        ),
    ]
