# Generated by Django 2.0.2 on 2021-07-06 20:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20201126_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='career',
            field=models.CharField(default='', max_length=100, verbose_name='carrera'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(default='', max_length=100, verbose_name='ciudad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.CharField(default='', max_length=100, verbose_name='pais'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='institution',
            field=models.CharField(default='', max_length=100, verbose_name='institucion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='state',
            field=models.CharField(default='', max_length=100, verbose_name='estado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='year_income',
            field=models.CharField(default=2021, max_length=100, verbose_name='anho_ingreso'),
            preserve_default=False,
        ),
    ]
