# Generated by Django 2.0.2 on 2021-07-12 19:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20210707_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sex',
            field=models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino'), ('N', 'No especifica')], default='', max_length=1, verbose_name='sexo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='ciudad'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='state',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='estado'),
        ),
    ]
