# Generated by Django 2.0.2 on 2021-07-17 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20210707_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='ciudad'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='state',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='estado'),
        ),
    ]
