# Generated by Django 2.0.2 on 2021-07-15 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20210712_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='career',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='carrera'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='year_income',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='anho_ingreso'),
        ),
    ]
