# Generated by Django 2.0.2 on 2021-07-23 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20210715_0925'),
        ('accounts', '0018_auto_20210716_2221'),
    ]

    operations = [
    ]
