# Generated by Django 2.0.2 on 2021-10-04 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_merge_20210723_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilecoach',
            name='habilitado',
            field=models.BooleanField(default=True),
        ),
    ]
