# Generated by Django 2.0.2 on 2021-10-19 21:25

import common.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='BigForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field0', models.CharField(blank=True, max_length=200, null=True, verbose_name='campo0')),
                ('field1', models.CharField(blank=True, max_length=200, null=True, verbose_name='campo1')),
                ('field2', models.CharField(blank=True, max_length=200, null=True, verbose_name='campo2')),
                ('field3', models.CharField(blank=True, max_length=200, null=True, verbose_name='campo3')),
                ('field4', models.CharField(blank=True, max_length=200, null=True, verbose_name='campo4')),
                ('field5', models.CharField(blank=True, max_length=200, null=True, verbose_name='campo5')),
                ('field6', models.FileField(blank=True, max_length=200, null=True, upload_to='', verbose_name='campo6')),
                ('field7', models.FileField(blank=True, max_length=200, null=True, upload_to='', verbose_name='campo7')),
                ('field8', models.FileField(blank=True, max_length=200, null=True, upload_to='', verbose_name='campo8')),
                ('field9', models.FileField(blank=True, max_length=200, null=True, upload_to='', verbose_name='campo9')),
            ],
            options={
                'verbose_name': 'bigForm',
            },
        ),
        migrations.CreateModel(
            name='BudgetRegistry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, null=True, verbose_name='descripción')),
                ('actual_budget', models.IntegerField(verbose_name='presupuesto')),
            ],
        ),
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='título')),
                ('num_projects', models.IntegerField(default=1)),
                ('has_projects', models.IntegerField(default=0)),
                ('has_evaluations', models.IntegerField(default=0)),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='fecha límite')),
                ('preparation_start', models.DateField(blank=True, null=True, verbose_name='fecha de inicio de prepación para equipos')),
                ('final_date', models.DateField(blank=True, null=True, verbose_name='fecha final')),
                ('award', models.CharField(max_length=50, verbose_name='premio')),
                ('rules', models.FileField(upload_to='', verbose_name='bases')),
                ('is_reviewed', models.BooleanField(default=False)),
                ('is_incubation', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'convocatoria',
                'ordering': ['id'],
                'permissions': (('is_jaku_staff', 'Is a Jaku staff'),),
            },
        ),
        migrations.CreateModel(
            name='DefaultTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True, verbose_name='nombre')),
            ],
            options={
                'verbose_name': 'tarea precargada',
                'verbose_name_plural': 'tareas precargadas',
            },
        ),
        migrations.CreateModel(
            name='DefaultWorkshop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True, verbose_name='nombre')),
                ('description', models.TextField(null=True, verbose_name='descripción')),
                ('temary', models.TextField(null=True, verbose_name='temario')),
            ],
            options={
                'verbose_name': 'taller predeterminado',
                'verbose_name_plural': 'talleres predeterminados',
            },
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
            ],
            options={
                'verbose_name': 'entidad',
                'verbose_name_plural': 'entidades',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True, verbose_name='título')),
                ('description', models.TextField(null=True, verbose_name='descripción')),
                ('date', models.DateField(blank=True, null=True, validators=[common.models.Event.validate_date], verbose_name='fecha')),
                ('image', models.ImageField(null=True, upload_to='', verbose_name='imagen')),
                ('link', models.CharField(blank=True, max_length=150, null=True, verbose_name='link')),
            ],
            options={
                'verbose_name': 'evento',
            },
        ),
        migrations.CreateModel(
            name='EventRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.Event', verbose_name='evento')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'registro a evento',
                'verbose_name_plural': 'registros a eventos',
            },
        ),
        migrations.CreateModel(
            name='FormConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=200, verbose_name='campo')),
                ('type', models.CharField(max_length=200, verbose_name='tipo')),
                ('label', models.CharField(max_length=200, verbose_name='etiqueta')),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Call')),
            ],
            options={
                'verbose_name': 'formConfig',
            },
        ),
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True, verbose_name='título')),
                ('description', models.TextField(null=True, verbose_name='descripción')),
                ('image', models.ImageField(null=True, upload_to='', verbose_name='imagen')),
            ],
            options={
                'verbose_name': 'noticia',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, null=True, verbose_name='codigo del emprendimiento')),
                ('leader', models.IntegerField(verbose_name='id lider de proyecto')),
                ('name', models.CharField(max_length=300, verbose_name='título del emprendimiento')),
                ('location', models.CharField(choices=[('1', 'AMAZONAS'), ('2', 'ANCASH'), ('3', 'APURIMAC'), ('4', 'AREQUIPA'), ('5', 'AYACUCHO'), ('6', 'CAJAMARCA'), ('7', 'CALLAO'), ('8', 'CUSCO'), ('9', 'HUANCAVELICA'), ('10', 'HUANUCO'), ('11', 'ICA'), ('12', 'JUNIN'), ('13', 'LA LIBERTAD'), ('14', 'LAMBAYEQUE'), ('15', 'LIMA'), ('16', 'LORETO'), ('17', 'MADRE DE DIOS'), ('18', 'MOQUEGUA'), ('19', 'PASCO'), ('20', 'PIURA'), ('21', 'PUNO'), ('22', 'SAN MARTIN'), ('23', 'TACNA'), ('24', 'TUMBES'), ('25', 'UCAYALI')], max_length=2, verbose_name='ubicación')),
                ('project_type', models.CharField(choices=[('1', 'BASE TECNOLÓGICA'), ('2', 'SOCIAL'), ('3', 'PRODUCTIVO')], max_length=1, verbose_name='tipo de proyecto')),
                ('summary', models.TextField(verbose_name='resumen del emprendimiento')),
                ('detail_description', models.TextField(verbose_name='descripción a detalle del emprendimiento')),
                ('detail_market_needs', models.TextField(verbose_name='justificación basado en necesidad del mercado')),
                ('members', models.TextField(verbose_name='miembros del equipo')),
                ('link_video', models.CharField(blank=True, max_length=200, null=True, verbose_name='link')),
                ('is_approved', models.CharField(choices=[('1', 'PENDIENTE'), ('2', 'APROBADO'), ('3', 'RECHAZADO')], default='1', max_length=1, verbose_name='estado del proyecto')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('eval_score', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='puntaje temporal de evaluacion')),
                ('budget', models.CharField(max_length=50, verbose_name='presupuesto')),
                ('call', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.Call', verbose_name='convocatoria')),
                ('coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.ProfileCoach', verbose_name='coach')),
            ],
            options={
                'verbose_name': 'proyecto',
                'permissions': (('is_entrepreneur', 'Is an entrepreneur'),),
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True, verbose_name='nombre')),
                ('assigned_date', models.DateField(blank=True, null=True, verbose_name='fecha de asignación')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='fecha limite')),
                ('is_done', models.BooleanField(default=False)),
                ('assign_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='asignado a')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Event', verbose_name='evento')),
            ],
            options={
                'verbose_name': 'tarea',
                'permissions': (('mark_as_done_task', 'Can mark  a task as done'),),
            },
        ),
        migrations.CreateModel(
            name='UserProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.Project', verbose_name='proyecto')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True, verbose_name='nombre')),
                ('description', models.TextField(null=True, verbose_name='descripción')),
                ('temary', models.TextField(null=True, verbose_name='temario')),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Call', verbose_name='convocatoria')),
            ],
            options={
                'verbose_name': 'taller',
                'verbose_name_plural': 'talleres',
            },
        ),
        migrations.AddField(
            model_name='call',
            name='entity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.Entity', verbose_name='entidad'),
        ),
        migrations.AddField(
            model_name='budgetregistry',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Project'),
        ),
        migrations.AddField(
            model_name='bigform',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Project'),
        ),
    ]
