# Generated by Django 2.0.2 on 2020-06-04 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='título')),
                ('due_date', models.DateField(blank=True, max_length=300, null=True, verbose_name='fecha límite')),
                ('award', models.CharField(max_length=50, verbose_name='premio')),
                ('rules', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='título')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='título')),
                ('call', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.Call', verbose_name='convocatoria')),
            ],
        ),
        migrations.AddField(
            model_name='call',
            name='entity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.Entity', verbose_name='entidad'),
        ),
    ]
