# Generated by Django 2.0.2 on 2020-06-06 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20200605_2359'),
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True, verbose_name='título')),
                ('description', models.TextField(null=True, verbose_name='descripción')),
            ],
            options={
                'verbose_name': 'noticia',
            },
        ),
    ]
