# Generated by Django 2.0.2 on 2020-06-06 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='imagen'),
        ),
    ]
