# Generated by Django 2.0.2 on 2020-06-07 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_new_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='titulo')),
                ('descripcion', models.CharField(max_length=50, verbose_name='descripcion')),
                ('fecha', models.DateField()),
            ],
        ),
    ]
