# Generated by Django 2.0.2 on 2020-06-07 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_evento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, null=True, verbose_name='título')),
                ('description', models.TextField(null=True, verbose_name='descripción')),
                ('date', models.DateField(blank=True, null=True, verbose_name='fecha')),
            ],
        ),
        migrations.DeleteModel(
            name='Evento',
        ),
        migrations.AlterField(
            model_name='call',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='fecha límite'),
        ),
    ]
