# Generated by Django 2.0.2 on 2020-06-08 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_auto_20200607_0755'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True, verbose_name='nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True, verbose_name='nombre')),
            ],
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'evento'},
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=200, null=True, verbose_name='título'),
        ),
        migrations.AddField(
            model_name='task',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.Event', verbose_name='evento'),
        ),
    ]
