# Generated by Django 2.0.2 on 2020-06-09 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_auto_20200608_1711'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='defaulttask',
            options={'verbose_name': 'tarea precargada', 'verbose_name_plural': 'tareas precargadas'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'tarea'},
        ),
    ]
