# Generated by Django 2.0.2 on 2020-06-10 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_auto_20200609_0953'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'permissions': (('mark_as_done_task', 'Can mark  a task as done'),), 'verbose_name': 'tarea'},
        ),
    ]
