# Generated by Django 2.0.2 on 2020-06-13 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_auto_20200609_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='final_date',
            field=models.DateField(blank=True, null=True, verbose_name='fecha final'),
        ),
        migrations.AddField(
            model_name='call',
            name='preparation_start',
            field=models.DateField(blank=True, null=True, verbose_name='fecha de inicio de prepación para equipos'),
        ),
        migrations.AddField(
            model_name='call',
            name='workshops',
            field=models.TextField(null=True, verbose_name='talleres'),
        ),
    ]
