# Generated by Django 2.0.2 on 2020-06-14 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_auto_20200613_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assign_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='asignado a'),
        ),
    ]
