# Generated by Django 2.0.2 on 2020-06-29 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0014_eventregister'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='imagen'),
        ),
        migrations.AddField(
            model_name='event',
            name='link',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='link'),
        ),
    ]
