# Generated by Django 2.0.2 on 2020-06-30 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0015_auto_20200629_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assigned_date',
            field=models.DateField(blank=True, null=True, verbose_name='fecha de asignación'),
        ),
    ]
