# Generated by Django 2.0.2 on 2020-07-02 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0016_task_assigned_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='call',
            options={'permissions': (('is_jaku_staff', 'Is a Jaku staff'),), 'verbose_name': 'convocatoria'},
        ),
    ]
