# Generated by Django 2.0.2 on 2020-07-02 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0017_auto_20200701_2128'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': (('is_entrepreneur', 'Is an entrepreneur'),), 'verbose_name': 'proyecto'},
        ),
    ]
