# Generated by Django 2.0.2 on 2020-07-06 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0018_auto_20200701_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='detail_description',
            field=models.TextField(default=1, verbose_name='descripción a detalle del emprendimiento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='detail_market_needs',
            field=models.TextField(default=1, verbose_name='justificación basado en necesidad del mercado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='location',
            field=models.CharField(default=1, max_length=300, verbose_name='ubicación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('1', 'BASE TECNOLÓGICA'), ('2', 'SOCIAL'), ('3', 'PRODUCTIVO')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='summary',
            field=models.TextField(default=1, verbose_name='resumen del emprendimiento'),
            preserve_default=False,
        ),
    ]
