# Generated by Django 2.0.2 on 2020-07-07 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0020_project_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=300, verbose_name='título del emprendimiento'),
        ),
    ]
