# Generated by Django 2.0.2 on 2020-07-15 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0021_auto_20200706_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('1', 'BASE TECNOLÓGICA'), ('2', 'SOCIAL'), ('3', 'PRODUCTIVO')], max_length=1, verbose_name='tipo de proyecto'),
        ),
    ]
