# Generated by Django 2.0.2 on 2020-07-15 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0022_auto_20200715_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='num_projects',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='project',
            name='code',
            field=models.CharField(max_length=100, null=True, verbose_name='codigo del emprendimiento'),
        ),
    ]
