# Generated by Django 2.0.2 on 2020-07-17 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0023_auto_20200715_1840'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntrepreneurRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='nombres')),
                ('last_name', models.CharField(max_length=50, verbose_name='nombres')),
                ('dni', models.CharField(max_length=8, verbose_name='dni')),
                ('phone_number', models.IntegerField(verbose_name='telefono/celular')),
                ('email', models.EmailField(max_length=254)),
                ('specialty', models.CharField(max_length=20, verbose_name='especialidad')),
                ('birthday', models.DateField(verbose_name='fecha de nacimiento')),
                ('reason_to_belong', models.TextField(verbose_name='motivo por el que quieren pertenecer a la red de emprendedores Jaku')),
            ],
        ),
    ]
