# Generated by Django 2.0.2 on 2020-07-17 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0024_entrepreneurrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EntrepreneurRequest',
        ),
    ]
