# Generated by Django 2.0.2 on 2020-07-22 18:16

import common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0025_delete_entrepreneurrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(blank=True, null=True, validators=[common.models.Event.validate_date], verbose_name='fecha'),
        ),
    ]
