# Generated by Django 2.0.2 on 2020-07-23 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0026_auto_20200722_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='location',
            field=models.CharField(choices=[('1', 'AMAZONAS'), ('2', 'ANCASH'), ('3', 'APURIMAC'), ('4', 'AREQUIPA'), ('5', 'AYACUCHO'), ('6', 'CAJAMARCA'), ('7', 'CALLAO'), ('8', 'CUSCO'), ('9', 'HUANCAVELICA'), ('10', 'HUANUCO'), ('11', 'ICA'), ('12', 'JUNIN'), ('13', 'LA LIBERTAD'), ('14', 'LAMBAYEQUE'), ('15', 'LIMA'), ('16', 'LORETO'), ('17', 'MADRE DE DIOS'), ('18', 'MOQUEGUA'), ('19', 'PASCO'), ('20', 'PIURA'), ('21', 'PUNO'), ('22', 'SAN MARTIN'), ('23', 'TACNA'), ('24', 'TUMBES'), ('25', 'UCAYALI')], max_length=2, verbose_name='ubicación'),
        ),
    ]
