# Generated by Django 2.0.2 on 2020-08-19 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0027_auto_20200723_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='has_projects',
            field=models.IntegerField(default=0),
        ),
    ]
