# Generated by Django 2.0.2 on 2020-10-07 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0029_project_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='is_approved',
            field=models.CharField(choices=[('1', 'PENDIENTE'), ('2', 'APROVADO'), ('3', 'RECHAZADO')], default='1', max_length=1, verbose_name='estado del proyecto'),
        ),
    ]
