# Generated by Django 2.0.2 on 2020-10-07 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0030_auto_20201007_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='is_approved',
            field=models.CharField(choices=[('1', 'PENDIENTE'), ('2', 'APROBADO'), ('3', 'RECHAZADO')], default='1', max_length=1, verbose_name='estado del proyecto'),
        ),
    ]
