# Generated by Django 2.0.2 on 2020-10-08 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0031_auto_20201007_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='link_video',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='link'),
        ),
        migrations.AddField(
            model_name='project',
            name='members',
            field=models.TextField(default=1, verbose_name='miembros del equipo'),
            preserve_default=False,
        ),
    ]
