# Generated by Django 2.0.2 on 2020-10-21 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0032_auto_20201008_1014'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventregister',
            options={'verbose_name': 'registro a evento', 'verbose_name_plural': 'registros a eventos'},
        ),
    ]
