# Generated by Django 2.0.2 on 2020-10-28 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0033_auto_20201020_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='has_evaluations',
            field=models.IntegerField(default=0),
        ),
    ]
