# Generated by Django 2.0.2 on 2020-10-28 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0034_call_has_evaluations'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='is_reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
