# Generated by Django 2.0.2 on 2020-10-31 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0035_call_is_reviewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_active',
            field=models.BooleanField(default=1, verbose_name='activo'),
            preserve_default=False,
        ),
    ]
