# Generated by Django 2.0.2 on 2020-11-01 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0036_project_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='activo'),
        ),
    ]
