# Generated by Django 2.0.2 on 2020-11-02 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20201020_2221'),
        ('common', '0037_auto_20201101_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='coach',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.ProfileCoach', verbose_name='coach'),
        ),
    ]
