# Generated by Django 2.0.2 on 2020-11-02 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0038_project_coach'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.ProfileCoach', verbose_name='coach'),
        ),
    ]
