# Generated by Django 2.0.2 on 2020-11-11 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0039_auto_20201101_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='activo'),
        ),
    ]
