# Generated by Django 2.0.2 on 2020-11-26 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0041_project_eval_score'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='call',
            options={'ordering': ['id'], 'permissions': (('is_jaku_staff', 'Is a Jaku staff'),), 'verbose_name': 'convocatoria'},
        ),
    ]
