# Generated by Django 2.0.2 on 2021-07-02 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0042_auto_20201126_0910'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultWorkshop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True, verbose_name='nombre')),
                ('description', models.TextField(null=True, verbose_name='descripción')),
                ('temary', models.TextField(null=True, verbose_name='temario')),
            ],
            options={
                'verbose_name': 'taller predeterminado',
                'verbose_name_plural': 'talleres predeterminados',
            },
        ),
    ]
