# Generated by Django 2.0.2 on 2021-07-17 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0043_defaultworkshop'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True, verbose_name='nombre')),
                ('description', models.TextField(null=True, verbose_name='descripción')),
                ('temary', models.TextField(null=True, verbose_name='temario')),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Call', verbose_name='convocatoria')),
            ],
            options={
                'verbose_name': 'taller',
                'verbose_name_plural': 'talleres',
            },
        ),
    ]
