# Generated by Django 2.0.2 on 2021-07-25 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0045_remove_call_workshops'),
        ('common', '0045_auto_20210721_0131'),
    ]

    operations = [
    ]
