# Generated by Django 2.0.2 on 2021-07-24 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0045_auto_20210721_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='leader',
            field=models.IntegerField(verbose_name='id lider de proyecto'),
        ),
    ]
