# Generated by Django 2.0.2 on 2021-08-07 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0046_auto_20210724_1033'),
        ('common', '0046_merge_20210725_1416'),
    ]

    operations = [
    ]
